### ISSUE TITLE
Intro.ipynb notebook

### ISSUE THREAD

**Issue by J-Christophe** [MizarWeb/ipymizar#2]
Hi,
In the example, the WMS server is not accessible (at least from WWW). It would be better to use a public WMS to play with the examples.

```
hysope_background = WMSLayer(
    url="http://hysope-proto.cst.cnes.fr/map/wms",
    layers="hysope-background-global",
)
```
Thanks

**Comment by serut** [comment]
Hello,
Thanks for your pull request @J-Christophe, I don't have such public WMS URL.
However, you need to commit only the required change, which is the URL to the WMS server. With your pull request, you also commited your output and automatic execution. Reopen the playbook, open the Edit menu, then click on Clear all output. Use the scissor to remove any empty cell. Thanks !
